[theme]
base = "light"
primaryColor = "#176B6C"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F5F7"
textColor = "#192C36"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
headless = true
address = "127.0.0.1"
